### Web Scraping
Retrieving the Table Dataset from Wikipedia

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
wiki_url = "https://en.wikipedia.org/wiki/List_of_largest_wastewater_treatment_plants"
webpage = requests.get(wiki_url).text
doc = BeautifulSoup(webpage, "html.parser")
doc.find_all('table')

In [12]:
table = doc.find( 'table', class_='wikitable sortable')
main_header = table.find_all('th')
main_header = [title.get_text().replace("\n", "") for title in main_header]

In [13]:
df = pd.DataFrame(columns = main_header)
df.columns

Index(['Plant name', 'City', 'Country', 'OpeningYear',
       'Dry-weathercapacity (m³ per day) ', 'Wet-weathercapacity (m³ per day)',
       'Area(km²)', 'Notes'],
      dtype='object')

In [14]:
df  = df.rename(columns={'Plant name':'Plant_Name','OpeningYear':'Opening_Year',\
    'Dry-weathercapacity (m³ per day) ':'DryWeather(CMD)','Wet-weathercapacity (m³ per day)':\
        'WetWeather(CMD)','Area(km²)':'Area(sqkm)'})
df.columns

Index(['Plant_Name', 'City', 'Country', 'Opening_Year', 'DryWeather(CMD)',
       'WetWeather(CMD)', 'Area(sqkm)', 'Notes'],
      dtype='object')

In [17]:
main_data = table.find_all('tr')
for row in main_data[1:]:   
    each_row = row.find_all('td')
    individual_row = [data.text.strip() for data in each_row]
    length = len(df)
    df.loc[length] = individual_row
df

,Plant_Name,City,Country,Opening_Year,DryWeather(CMD),WetWeather(CMD),Area(sqkm),Notes
0,Jean-R.-Marcotte Wastewater Treatment Plant[1],Montreal,Canada,1984,"2,780,000","7,600,000",0.67,Secondary treatment planned for 2023.[2]
1,Detroit Wastewater Treatment Plant[3],Detroit,USA,1940,2 460 000,6 435 000,0.53,Wet-weather secondary treatment capacity limit...
2,Stickney Water Reclamation Plant[4],Chicago,USA,1930,2 665 000[5],5 450 000[6],1.67,
3,Blue Plains Advanced Wastewater Treatment Plan...,Washington D.C.,USA,1937,1 450 000,4 073 000,0.62,Secondary treatment since 1959. Enhanced nutri...
4,Deer Island Waste Water Treatment Plant,Boston,USA,1968,1 438 000,4 542 000,0.6[8],Full secondary treatment since 1995.
5,Abu Rawash Wastewater treatment plant,Giza,Egypt,2021,"1,600,000",,1.39,Secondary treatment since 2021.
6,Atotonilco de Tula Plant[9],Mexico City,Mexico,2015,2 000 000,3 000 000,,
7,Hyperion Water Reclamation Plant[10],Los Angeles,USA,1925,1 041 000,3 000 000,0.81,Wet-weather secondary treatment (since 1950) c...
8,Kuryanovo wastewater treatment facilities[11],Moscow,Russia,1950,2 200 000,,,
9,Lyuberetskiye wastewater treatment facilities[12],Moscow,Russia,1963,3 000 000,,,
10,Seine Aval Wastewater Treatment Plant[13],Paris,France,1940,1 460 000,2 900 000,8,
11,Shanghai Zhuyan I Wastewater Treatment Plant[14],Shanghai,China,2004,1 700 000,,,
12,Stonecutters Island Sewage Treatment[15],Hong Kong,China,2001,,2 765 000[16],,
13,Bailonggang Wastewater Treatment Plant,Shanghai,China,1999,2 000 000,,,
14,Gabal el Asfar Wastewater Treatment Plant,Cairo,Egypt,,1 700 000,2 500 000[17],1.63,
15,Beckton Sewage Treatment Works,London,UK,1864,,2 330 000,1,
16,Morigasaki Water Reclamation Center[18],Tokyo,Japan,1966,,1 540 000,0.41,
17,Beijing Huaifang Water Plant,Beijing,China,2017,600 000[19],,0.16[20],Built underground.
18,Western Treatment Plant,Melbourne,Australia,1897,485 000,,105[21],
19,Dasherkandi Sewage Treatment Plant,Dhaka,Bangladesh,2023,350 000,500 000,0.26,Largest sewage treatment plan in South Asia.[22]
20,McAlpine Creek Wastewater Treatment Plant,"Charlotte, N.C.",USA,1966,"290,950",,,
21,Jean-R.-Marcotte Wastewater Treatment Plant[1],Montreal,Canada,1984,"2,780,000","7,600,000",0.67,Secondary treatment planned for 2023.[2]
22,Detroit Wastewater Treatment Plant[3],Detroit,USA,1940,2 460 000,6 435 000,0.53,Wet-weather secondary treatment capacity limit...
23,Stickney Water Reclamation Plant[4],Chicago,USA,1930,2 665 000[5],5 450 000[6],1.67,
24,Blue Plains Advanced Wastewater Treatment Plan...,Washington D.C.,USA,1937,1 450 000,4 073 000,0.62,Secondary treatment since 1959. Enhanced nutri...
25,Deer Island Waste Water Treatment Plant,Boston,USA,1968,1 438 000,4 542 000,0.6[8],Full secondary treatment since 1995.
26,Abu Rawash Wastewater treatment plant,Giza,Egypt,2021,"1,600,000",,1.39,Secondary treatment since 2021.
27,Atotonilco de Tula Plant[9],Mexico City,Mexico,2015,2 000 000,3 000 000,,
28,Hyperion Water Reclamation Plant[10],Los Angeles,USA,1925,1 041 000,3 000 000,0.81,Wet-weather secondary treatment (since 1950) c...
29,Kuryanovo wastewater treatment facilities[11],Moscow,Russia,1950,2 200 000,,,
30,Lyuberetskiye wastewater treatment facilities[12],Moscow,Russia,1963,3 000 000,,,
31,Seine Aval Wastewater Treatment Plant[13],Paris,France,1940,1 460 000,2 900 000,8,
32,Shanghai Zhuyan I Wastewater Treatment Plant[14],Shanghai,China,2004,1 700 000,,,
33,Stonecutters Island Sewage Treatment[15],Hong Kong,China,2001,,2 765 000[16],,
34,Bailonggang Wastewater Treatment Plant,Shanghai,China,1999,2 000 000,,,
35,Gabal el Asfar Wastewater Treatment Plant,Cairo,Egypt,,1 700 000,2 500 000[17],1.63,
36,Beckton Sewage Treatment Works,London,UK,1864,,2 330 000,1,
37,Morigasaki Water Reclamation Center[18],Tokyo,Japan,1966,,1 540 000,0.41,
38,Beijing Huaifang Water Plant,Beijing,China,2017,600 000[19],,0.16[20],Built underground.
39,Western Treatment Plant,Melbourne,Australia,1897,485 000,,105[21],
40,Dasherkandi Sewage Treatment Plant,Dhaka,Bangladesh,2023,350 000,500 000,0.26,Largest sewage treatment plan in South Asia.[22]
41,McAlpine Creek Wastewater Treatment Plant,"Charlotte, N.C.",USA,1966,"290,950",,,

In [18]:
df.to_csv(
    r'C:\Users\User\Downloads\Documents\Largest WWTP\raw_largewwtp.csv', index=False)